### ISSUE TITLE
Update User Data on Each Login

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#109]
The user data stored in VizHub is from the first time a user logs in.

If a user updates something in their GitHub profile, the changes are not propagated into VizHub.

Ideally, they should be, so that for example if a person changes their "name" field in GitHub, then authenticates with GitHub to VizHub, VizHub should display their updated name.

(FWIW there was a bug in the past where full name was using an outdated field - so this change may fill in lots of missing names over time)

**Comment by curran** [comment]
It turns out about 1/4 of all users have a `displayName` as `null` coming from GitHub OAuth.

**Comment by curran** [comment]
This change might fill in some of these missing full name fields:

![image](https://user-images.githubusercontent.com/68416/85204129-3e8bf700-b2e0-11ea-8b59-f97a33a49458.png)

**Comment by kalpesh05** [comment]
I have modified bit to update user basic details on each login , you can look at it tell if any changes needed
