### ISSUE TITLE
Mirror to Bl.ocks.org

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#129]
As a visualization author, I want to mirror my visualization on bl.ocks.org, so that it is permanently archived there, and can benefit from the bl.ocks.org ecosystem.

Please :+1: this issue to help prioritize this task in our [backlog](https://github.com/datavis-tech/vizhub-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by micahstubbs** [comment]
excited about this one

**Comment by micahstubbs** [comment]
would be really cool to mirror each vizhub example as a github gist 💡

**Comment by curran** [comment]
Yes that's exactly the idea here! I'm planning on studying how Blockbuilder does the Gist creation and saving for implementing this feature.

**Comment by micahstubbs** [comment]
here's a starting point: 

https://github.com/enjalot/blockbuilder/blob/master/server.js#L299

![screen shot 2018-10-11 at 7 27 24 pm](https://user-images.githubusercontent.com/2119400/46844399-b542c400-cd8b-11e8-8593-5a17a78a41d5.png)

**Comment by curran** [comment]
Thanks a ton! Will research there.

**Comment by curran** [comment]
Related newer topic: [Vote
Feature Request: Sync to Gist](https://discourse.vizhub.com/t/feature-request-sync-to-gist/87).

**Comment by curran** [comment]
Closing in favor of https://github.com/datavis-tech/vizhub-issue-tracker/issues/301
