### ISSUE TITLE
Per-file Cursor and Undo History

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#146]
As a visualization author, I want each file to have independent cursor placement and undo history, so that I don't experience unexpected glitches while working.

https://codemirror.net/doc/manual.html#api_doc

**Comment by curran** [comment]
Working prototype of this feature is here https://github.com/datavis-tech/vizhub-io/tree/6cd0c290d48183d6fb4858ad8ff0ba8caffe1b6f

**Comment by curran** [comment]
Mentioned today by @razpudding as a big point of frustration for students while using VizHub.

>This would be a reason they switch out of VizHub and into local development.

**Comment by stushurik** [comment]
@curran shell we preserve a cursor and history on an editor close?

**Comment by curran** [comment]
Yes.

**Comment by stushurik** [comment]
@curran that means that we will need to store state (history, cursors) on viz page level
