### ISSUE TITLE
Display Errors Inside Editor

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#157]
Errors are already being displayed well in the console.

What if they could also be displayed inside the editor?

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/46570376-bb4a3680-c980-11e8-818d-d321519248cb.png)
https://codemirror.net/demo/lint.html

![image](https://user-images.githubusercontent.com/68416/46570379-c8ffbc00-c980-11e8-8399-cd70f4617a6e.png)
https://codemirror.net/demo/widget.html

**Comment by curran** [comment]
Blockbuilder does it like this https://github.com/enjalot/blockbuilder/blob/master/public/js/components/editor__error-marker.js

**Comment by stushurik** [comment]
https://github.com/eslint/website/tree/master/src/js/demo
