### ISSUE TITLE
Collapsible file panel(section)

### ISSUE THREAD

**Issue by stushurik** [datavis-tech/vizhub-issue-tracker#166]
As a visualization author I want to be able to collapse files panel(section) so that more space on the screen is available for code and preview

Please :+1: this issue to help prioritize this task in our [backlog](https://github.com/datavis-tech/vizhub-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by curran** [comment]
Yes! This is a great idea. Do you have UI designs in mind for how would it look like collapsed, and how it would be un-collapsed? Or any other tools in mind that have this feature? If so feel free to share sketches or screenshots!

Related to

 * **Show & Hide Editor** #99
 * **Mobile Optimization** #167

**Comment by curran** [comment]
This tool has this feature https://editor.p5js.org/p5/sketches/SkEKiqPtX

![peek 2018-11-05 18-28](https://user-images.githubusercontent.com/68416/47999459-a6e88d80-e128-11e8-8948-f13947984653.gif)

**Comment by curran** [comment]
Also in this tool https://snack.expo.io/

![peek 2018-11-15 14-53](https://user-images.githubusercontent.com/68416/48542877-4571ad00-e8e6-11e8-820a-c60c60874d8f.gif)

**Comment by curran** [comment]
Hey @stushurik I was just going through the backlog and realized this is done! Thanks for the original suggestion, which did inspire parts of the redesign effort.
