### ISSUE TITLE
Profile Sidebar: Public vs. Private

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#208]
This issue is about adding the "public" and "private" sections here.

![image](https://user-images.githubusercontent.com/68416/82008187-fc64fb00-9639-11ea-93bc-2f088b1dfb18.png)

Active/inactive style:

![image](https://user-images.githubusercontent.com/68416/84547381-6b814e00-acd1-11ea-95fe-75173692742e.png)

For a first pass, simplest solution probably is to leave the profile backend and query as-is, and just filter on the client side what is shown.

The state of what section is open should be a part of the URL, possibly a new parameter like `?section=public`

**Comment by nitanagdeote** [comment]
Note: the side buttons should be sticky (meaning not scroll) like Facebook.

**Comment by curran** [comment]
Alternative design:

![image](https://user-images.githubusercontent.com/68416/84546963-82737080-acd0-11ea-8fe6-556fb0f28b54.png)

Maybe one variant if you are logged in and looking at your own profile, and another if you're looking at someone else's? Not sure...

**Comment by milafrerichs** [comment]
@curran just for clarification:
this is now in the profile and not on the dashboard? because the Figma designs have this for the dashboard and not for the profile.

**Comment by curran** [comment]
@milafrerichs Great quesion - I've been thinking about this as well, whether it should be its own new/separate page, or a variant of the profile page.

My current thinking is this: the so-called "Dashboard" is what you get when you are:
 * Logged in, and
 * Viewing your own profile page

So, effectively this is an evolution of the profile page itself, with the addition of the sidebar for that particular case.
