### ISSUE TITLE
Link to Line Number

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#213]

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/82123327-cf623680-9766-11ea-8850-26b216183740.png)

GitHub's design

**Comment by curran** [comment]
Interactions:
 * Click on gutter (cursor: pointer)
 * Copy URL
 * Go to URL --> editor scrollIntoView, show highlighted line

**Comment by stushurik** [comment]
@curran would you like to see either context menu when user clicks on gutter with copy option or copy immediately after user clicks on gutter ?

**Comment by curran** [comment]
I'm thinking something like this:
 * User can click on the line number itself (in the left gutter of the code editor)
 * After clicking on the number, the line is highlighted and a parameter is added to the URL
 * The user can copy the link manually from the URL bar

More UI elements can be added later, such as a menu or a copy interaction, but for the first pass these are not needed. Thanks!

**Comment by curran** [comment]
Concrete tasks:

 * [ ] Make line numbers appear clickable (add `cursor: pointer` CSS)
 * [ ] On click, add a parameter to the URL (for example `?line=43` or something like that)
 * [ ] When parameter is present, style that line differently (perhaps a yellow semi-transparent overlay)
 * [ ] Make sure that if a user navigates directly to the copied URL, the line is highlighted
 * [ ] Finishing touches: Make sure that if a user navigates directly to the copied URL, the highlighted line automatically scrolls into view.
