### ISSUE TITLE
Saving/Saved Indicator

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#214]
We can use `doc.whenNothingPending` from [ShareDB](https://github.com/share/sharedb)

**Comment by stushurik** [comment]
@curran any ideas how it might look like in ui?

**Comment by curran** [comment]
![image](https://user-images.githubusercontent.com/68416/89103794-87a49000-d3e2-11ea-91f8-aa6dc18ecb36.png)

**Comment by curran** [comment]
From https://www.figma.com/file/vpKCkMVidrGVU8R3hlkJqU/Vizhub-(Copy)?node-id=297%3A3219

**Comment by curran** [comment]
As a first pass we can add that widget in just one place.

![image](https://user-images.githubusercontent.com/68416/89103958-ac4d3780-d3e3-11ea-8594-c8d8998daa74.png)
