### ISSUE TITLE
GitHub Integration (epic)

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#222]
Ideas:
 * Sync Viz to Gist
 * VizHub maintains a branch from a Git repo, auto push to GitHub remote.
 * VizHub maintains the content of a subdirectory?

**Comment by sjengle** [comment]
Would love to see this for teaching datavis courses!

**Comment by curran** [comment]
Thanks @sjengle ! Just exploring this UI for inspiration:

https://vega.github.io/editor/?#/

![image](https://user-images.githubusercontent.com/68416/83451324-b4f5b180-a424-11ea-911d-afc7f454d6e7.png)

![image](https://user-images.githubusercontent.com/68416/83451359-cccd3580-a424-11ea-9a28-e043647b953e.png)

Some great ideas there..

**Comment by curran** [comment]
Ideas for this feature:

 * Phase I can be Gist integration #231
 * Phase II can be GitHub repository integration #232
