### ISSUE TITLE
Funky selection bug

### ISSUE THREAD

**Issue by Razpudding** [datavis-tech/vizhub-issue-tracker#226]
I've been experiencing a weird bug. When I switch files, my cursor changes to a block and I can't input text until I press command+v. When I do so the cursor changes back and I can continue working normally.

However, there is apparently some functionality happening here because if I don't press cmd+v immediately, some command will be triggered on key presses. This just resulted in my html being deleted. cmd+z doesn't work when I want to restore my work so I'll have to rewrite it.

**Comment by Razpudding** [comment]
It looks like a special mode is activated by default everytime I switch files.

**Comment by curran** [comment]
Thanks for the feedback! This is Vim mode being activated/deactivated. It should remember the activation setting from the previous session. A few ideas for directions to improve this experience:
 * Possibly best to _always_ have Vim mode off when the page is loaded. Then, if you want to work in Vim mode, you'd need to hit Alt+V to get into it each time a page is loaded. This would address the problem of being in Vim mode to start with and not realizing it.
 * There should be a more clear indicator that Vim mode is active or not active. Currently the only way to tell is that there's a fat cursor, which means you're in Vim mode. I realize this is not clear at all.

**Comment by Razpudding** [comment]
Ah yes that fixed it! It was so annoying to work around that problem. And I tried checking your blog posts to see if new features had been added that would explain this mode. I couldn't find anything about it in either the general article about vizhub or any of the posts. This relates to an issue I wrote on discourse (which seems to be down, or maybe you moved to github issues+Kanban and I missed it). There should be a manual page that explains all the Vizhub features.
You can close this issue or use it to track a more permanent solution, up to you :)

**Comment by curran** [comment]
Nice! Vim mode is mentioned briefly in https://datavis.tech/vizhub/, but could use more detail.

I think I'll keep this issue open for now, as the current behavior is not intuitive.

Hope to release some concrete improvements around this soon!

**Comment by curran** [comment]
Closing in favor of #254
