### ISSUE TITLE
Handle short screens for dialogs

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#227]
![image](https://user-images.githubusercontent.com/68416/82739410-4ff7d880-9d0d-11ea-9b72-81820b996374.png)

Maybe enable scroll?

Top parts should be always visible.

**Comment by stushurik** [comment]
@curran would be better to make site responsive? I mean instead of check if device is mobile, check screen size using media queries. 
In this case user can see mobile layout

**Comment by curran** [comment]
I'm not opposed to it.

Another related feature I'd like to enable: in mobile, switch from portrait to landscape (turn the phone sideways and the layout should update).
