### ISSUE TITLE
Transform Presence

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#228]
* [x] Transform presence

**Comment by stushurik** [comment]
@curran could you please give more context ?

**Comment by curran** [comment]
Sure. If you're in a collaborative session with someone and you make a change, their presence icon location is not updated correctly at the moment if the text beneath if moves around. This is because presence is not transformed.

There is an old implementation for presence transformation here https://github.com/datavis-tech/json0/blob/master/lib/json0.js#L662 

That version is using an outdated prototype API for presence transformation, which has since been superceded by this new presence implementation and API https://github.com/share/sharedb/pull/322, which the current VizHub presence feature is built on.

The task at hand here is to migrate that old implementation for presence transformation into the new VizHub presence implementation. It's stubbed here vizhub/packages/json0-with-presence/index.js

I'm not sure how far the old ShareDB presence API proposal and new ShareDB presence API have diverged. Best case scenario, they match.
