### ISSUE TITLE
Optimize home page for mobile

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#229]
![image](https://user-images.githubusercontent.com/68416/83423294-bf9a5180-a3f8-11ea-92c0-f6b9745e6d9e.png)

**Comment by curran** [comment]
Design decisions open to be made here. Any improvement welcome as a first pass! Maybe flow all 3 items vertically, and centered?

**Comment by stushurik** [comment]
@curran please check out my suggestions in slack
