### ISSUE TITLE
GitHub Repository Integration

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#232]

**Comment by curran** [comment]
GitHub Actions on commit

**Comment by stushurik** [comment]
https://developer.github.com/v3/git/

**Comment by curran** [comment]
Nice. Want to work on this? I'd say go for it if you have some momentum! GitHub integration will vastly improve VizHub.

Just be sure to keep in sync with @denisemauldin who will be working on the Gist integration, which may share some APIs.

**Comment by denisemauldin** [comment]
Happy to follow @stushurik lead!

**Comment by stushurik** [comment]
@curran @denisemauldin not sure that I will have enough time a few upcoming weeks for such a big issue.
Moreover I think @curran should decide what he want to achieve. For example if vizhub would be fully integrated with guthub repository how would it treat conflicts if one push commits outside vizhub? So  i think we need clear roadmap for this feature

**Comment by curran** [comment]
I agree. I will do some thinking about desired behavior. I realize it's a huge feature.

I'd be curious to see what other tools, like CodeSandbox, do in terms of GitHub integration. We may be able to take inspiration from how that behaves.

**Comment by stushurik** [comment]
As for me, ideal case if vizhub would be fully integrated git client, so that it would be possible to do commits and than I can clone repo on my laptop and continue working. And vice versa

**Comment by curran** [comment]
Yes, that would be ideal.

Another idea: VizHub as a desktop app that can edit local files.

**Comment by curran** [comment]
Closing in favor of https://github.com/datavis-tech/vizhub-issue-tracker/issues/301
