### ISSUE TITLE
Embedding Phase I - Make Snippet Work

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#258]

**Comment by stushurik** [comment]
@curran could you please share some technical ideas how would you like to implement it?
I just copy pasted iframe from viz's viewer and paste it html document and it works. we can allow user to copy that iframe via ui but i am not sure this aligned with your vision

**Comment by curran** [comment]
@stushurik I'm thinking it can load the viz page with a parameter set, like `?embed`. That will load the app as usual, and the rendering will be quite similar to full screen mode, but using this design instead (with footer added).

![image](https://user-images.githubusercontent.com/68416/89104067-84120880-d3e4-11ea-9f87-9b24a0e4090d.png)

That URL pattern should be whitelisted for cross domain iFrame embedding. All other URLs should be blacklisted. We may need to set https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/X-Frame-Options from the Express side https://stackoverflow.com/questions/46998540/how-to-set-x-frame-options-in-express-js-node-js
