### ISSUE TITLE
Show Forks Count in viz page

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#279]

**Comment by curran** [comment]
Closing in favor of more detailed:
 * Show Forks List (who forked? thumbnails for each fork) #287
 * Show Forks Count in viz page #279

**Comment by stushurik** [comment]
@curran do you have icon for this feature?

**Comment by curran** [comment]
Please put the number next to the existing fork icon. Thanks!

![image](https://user-images.githubusercontent.com/68416/85203524-67aa8880-b2dc-11ea-87cc-de31fd4075c9.png)

**Comment by curran** [comment]
Phase 1 is to just add the number.

Phase 2 is to make it clickable, and build out UI that shows the forks - tracked separately in https://github.com/datavis-tech/vizhub-issue-tracker/issues/287
