### ISSUE TITLE
Show Forks List (who forked? thumbnails for each fork)

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#287]
Depends on Show Forks Count in viz page #279 - that "showing" can link into a view that shows a forks list - that new page is what this issue is about.

**Comment by stushurik** [comment]
@curran whats should be on this page? just a list of forks?
any preferences how it should look like?

**Comment by curran** [comment]
Just a list of forks, similar to current profile page. That can be phase I.

Phase II should include a title area that says "Forks of " followed by the title of the viz.

Lots of open design questions. I'm most interested in a rough first working version.

**Comment by stushurik** [comment]
@curran phase 1 version: https://github.com/curran/vizhub/pull/250
