### ISSUE TITLE
New Navbar Design

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#290]
Concrete tasks here:
 * [x] Change navbar background color
 * [x] Use designed height (from Figma)
 * [x] Implement redesigned Search box
 * [x] Add search icon to Search box
 * [x] Implement redesigned profile menu button (sign in / profile + arrow)
 * [x] Implement redesigned profile menu dropdown
 * [x] Make the navbar sticky
 * [x] Make it work on mobile (no designs - some creativity required)

(Home and About links can be ignored for the first pass)

![image](https://user-images.githubusercontent.com/68416/84547071-b77fc300-acd0-11ea-9ac9-1dd504c045a2.png)

![image](https://user-images.githubusercontent.com/68416/84547100-cd8d8380-acd0-11ea-8e54-320c5498b1b4.png)

![image](https://user-images.githubusercontent.com/68416/84547164-00377c00-acd1-11ea-9829-6322464fd9d7.png)

https://www.figma.com/file/kUpMM9rcOGg7T62tYBAN2o/Vizhub?node-id=7%3A955

**Comment by nitanagdeote** [comment]
This navbar should be sticky (meaning not scroll) like Facebook.

**Comment by curran** [comment]
A note from https://github.com/datavis-tech/vizhub-issue-tracker/issues/335 - clicking on the search icon should execute te search (same as Enter key).

**Comment by nitanagdeote** [comment]
Its all there!

**Comment by curran** [comment]
Closed as first pass is done.
