### ISSUE TITLE
Marketing Content for VizHub

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#314]
Similar to https://circleci.com/ layout

![image](https://user-images.githubusercontent.com/13540669/84546512-7a670100-accf-11ea-9f3c-47d841d99248.png)

On the top of the home page.

**Comment by curran** [comment]
Original designs from Stamen:

![image](https://user-images.githubusercontent.com/68416/84546834-31637c80-acd0-11ea-959e-b5abe27c0eb4.png)

Second round designs from Stamen ([Figma Link](https://www.figma.com/file/kUpMM9rcOGg7T62tYBAN2o/Vizhub?node-id=0%3A1)):

![image](https://user-images.githubusercontent.com/68416/84546874-4e984b00-acd0-11ea-8c17-73345e20061f.png)

**Comment by curran** [comment]
Featured viz grid

**Comment by curran** [comment]
By the way - this was implemented in the past but was temporarily disabled.

Code is here `src/pages/HomePage/Banner/index.js`.

**Comment by nitanagdeote** [comment]
### Vizhub feature list 

- Real time environment
Collaboration
Export files
Forking
line number sharing
Unfirling
ES6 Modules
Upvote
Presentation mode viz
Use react

**Comment by nitanagdeote** [comment]
There are other solid features that are in the backlog of kanban...
like **Github integration**
Any other solid feature?

**Comment by nitanagdeote** [comment]
@curran Suggesting to move the video link on the front page in some section like 'Learn more about data vizualization'.

**Comment by nitanagdeote** [comment]
Suggesting - Thumbnail should have 'rename' feature? so that its possible to change the name of the file right there(user friendly)

**Comment by curran** [comment]
Great idea! Created a new issue for that **Rename from Viz Preview #327**.
