### ISSUE TITLE
Syntax error- font size can be bigger as more space on the right side.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#319]
https://vizhub.com/nitanagdeote/5ba43c915d1c4da6809fc249c97ea211?edit=files&file=index.js

**Comment by nitanagdeote** [comment]
The link is not showing the syntax error here at </div

**Comment by curran** [comment]
Can you share a screenshot?

The size is already pretty big. Here's what I'm seeing:

![image](https://user-images.githubusercontent.com/68416/86487165-655c1b80-bd2b-11ea-83a3-68c5195d1b95.png)

The error text should be even bigger than that?
