### ISSUE TITLE
Bug: Can't Open Editor Directly After Forking

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#328]
To reproduce:
 * Fork
 * Click "Open Editor" - nothing happens and an error is shown

**Comment by stushurik** [comment]
@curran @nitanagdeote I can't reproduce it tried on all envs: prod, staging and local

**Comment by curran** [comment]
Same here. Closing as unable to reproduce. Thanks @stushurik for having a look!
