### ISSUE TITLE
Finesse Styling for Upvote Count in Viz Previews

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#338]
* Fill color should be white, not black
 * Previous layout should be preserved
 * Upvote icon should align with username

![image](https://user-images.githubusercontent.com/68416/85738911-64454180-b6ce-11ea-8046-7f7a4a515821.png)

**Comment by nitanagdeote** [comment]
@curran  0 up votes: should it be there?

**Comment by curran** [comment]
I think so, yes.

**Comment by nitanagdeote** [comment]
> I think so, yes.

ya..makes sense

**Comment by nitanagdeote** [comment]
> > I think so, yes.
> 
> ya..makes sense

Looks great on home page! 
Should the icon upvote little smaller?

**Comment by curran** [comment]
I think the consistency in size between here and the viz view page is nice.

Maybe it could be smaller though...

**Comment by nitanagdeote** [comment]
> I think the consistency in size between here and the viz view page is nice.
> 
> Maybe it could be smaller though...

On Vizhub home page only I am talking about. Its little bigger than a profile icon. My understanding is it should be smaller than that and also in the future we will have fork icon next to it.
