### ISSUE TITLE
Editing the code results in "TypeError: Cannot read property 'column' of undefined"

### ISSUE THREAD

**Issue by Z-Richard** [datavis-tech/vizhub-issue-tracker#353]
Vizhub has been almost impossible for me to use this morning, as this weird bug arose every time I tried to edit the code. Even adding an empty space at the end of a line would result in this error. This did not occur when I refreshed the page, but only after I edited the code. I also noticed that `bundle.js` was not updated accordingly when I changed my code elsewhere.

I am not sure whether this problem is replicable since I am using a VPN to visit Vizhub as it is blocked by the Great Firewall, and it can certainly be an issue on my side. For reference, my viz is @ https://vizhub.com/Z-Richard/63e72fcf82b14b379b58a6b9ec36692f.

**Comment by curran** [comment]
Thank you so much for reporting this! Investigating a fix now.

**Comment by curran** [comment]
@Z-Richard A fix for this has been deployed. Thank you for catching this and reporting.

Very exciting mapping work you are doing. Looking forward to see it come together!
