### ISSUE TITLE
After deletion of fork title remains the same but should be profile page title

### ISSUE THREAD

**Issue by stushurik** [datavis-tech/vizhub-issue-tracker#356]
![image](https://user-images.githubusercontent.com/3383021/85946440-ffe3e580-b94c-11ea-8ef9-6ee9f4a57391.png)

**Comment by stushurik** [comment]
@curran fyi

**Comment by curran** [comment]
Yes, another good catch! Stale title is a long standing problem. Thank you for making this issue for it.
