### ISSUE TITLE
Search for Users

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#36]
As a user, I want to be able to search for users, so that I can find the profile page of a specific person.

**Comment by curran** [comment]
Idea: make it similar to Blockbuilder search in terms of results layout http://blockbuilder.org/search#text%3Dvoronoi

**Comment by curran** [comment]
Maybe VizHub search could just open up Blockbuilder search? There's loads more content there anyway.

**Comment by curran** [comment]
And I wonder, @micahstubbs, what would it take to have Blockbuilder search results include entries from VizHub?

Related to the idea *Mirror to Bl.ocks.org* #129

**Comment by micahstubbs** [comment]
@curran good question.  the high level answer is that it could be achieved by including vizhub example metadata in the blockbuilder search indexing process.

this could be done a few different ways

**Comment by micahstubbs** [comment]
one easy-from-bb search's perspective way would be for vizhub to also provide the github gist APIs that blockbuilder search index calls

**Comment by micahstubbs** [comment]
will get to a bigger screen in the next couple days and be able to give a more detailed answer about just what those APIs are.  with enough motivation, you could probably also figure this out from looking at the bb search repo, perhaps at gist-meta.coffee

**Comment by curran** [comment]
@micahstubbs I was poking around trying to find the "github gist APIs that blockbuilder search index calls", but was having trouble locating it. Would you be able to point me towards the code that would need to be modified/extended?

I'd be open to implementing approximations of the gist APIs in the VizHub server. That does seem the path of least resistance.

**Comment by micahstubbs** [comment]
to be honest, I think that this would be the path of least resistance, and be most robust to changes in the future https://github.com/datavis-tech/vizhub-ui/issues/129

**Comment by curran** [comment]
Related to newer versions of this issue:

 * [Vote Feature Request: Search](https://discourse.vizhub.com/t/feature-request-search/19/2)
 * [Vote Feature Request: GitHub Integration](https://discourse.vizhub.com/t/feature-request-github-integration/37)
 * [Feature Request: Sync to Gist](https://discourse.vizhub.com/t/feature-request-sync-to-gist/87)

**Comment by curran** [comment]
Idea: retrofit working UI for adding collaborators to work with the search bar (as autocomplete dropdown).

Desired behavior:
 * Search for a term and hit enter --> search for visualizations (happens now)
 * As you're typing, see autocomplete for users, click autocomplere result --> navigate to profile (new feature)
