### ISSUE TITLE
Bug when forking after error occurs

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#365]
![image](https://user-images.githubusercontent.com/68416/86038958-c1fbc580-ba0f-11ea-9d84-52e15b8fca9a.png)

 It only happens when there is first an error when you try to edit someone else's viz, and then try to fork. Forking directly (without first attempting to edit) seems to work fine.

**Comment by stushurik** [comment]
@curran closed by pr for #346

**Comment by curran** [comment]
Agreed.
