### ISSUE TITLE
(Styling) VizHub community: too close to the left

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#368]
The text VizHub Community on home page is touching the left corner.
![vizHubCommunity](https://user-images.githubusercontent.com/13540669/86191094-2738df00-bb14-11ea-8926-ca97f5463daa.png)

**Comment by curran** [comment]
Nice find!

@stushurik Would you mind taking a pass at this? It should ideally be the same padding/margin as the VizHub logo. Thanks!

**Comment by curran** [comment]
The mobile case should be considered and tested as well.
