### ISSUE TITLE
Show Who Upvoted

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#370]
As a viz author, I want to know who has upvoted a given viz.

Idea for low hanging fruit improvement: add usernames list to the tooltip on the upvote icon.

![image](https://user-images.githubusercontent.com/68416/86261782-006abf00-bb8d-11ea-8510-5282c0baab6d.png)

There can be a more designed "phase II", but this would be a great easy change to make.

**Comment by stushurik** [comment]
@curran it is not so low hanging as it expected, since for example home page does not contains upvoters profiles (only ownerUsers which is not the same + it's fetched only on initial load), looks like it requires loading upvotes username on hover or on click. Any ideas ?

**Comment by curran** [comment]
@stushurik Aahhh yes you're right. Indeed, this will take more work than just exposing fields already in the client.

If it might simplify things, IMO this feature is only required for the viz view page, not in previews.

So, maybe on hover we could invoke an endpoint that looks up usernames for each user id. There's already an interactor `userGateway.getUsers(ownerUserIds)`.
