### ISSUE TITLE
Copy Paste editor line 

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#371]
Copy line in one viz editor does not paste in other viz editor
 with " CTRL+c"  and  " CTRL+v". Also does not paste outside VizHub like in browser.

**Comment by curran** [comment]
Copy-paste works as expected (with CTRL+c and CTRL+v) if you're not in Vim mode.

Vim mode does copy-pasting with Vim commands Y and P.

**Comment by curran** [comment]
ALT+p

**Comment by nitanagdeote** [comment]
Are you sure? It's not working.

**Comment by curran** [comment]
Sorry - ALT+v

**Comment by curran** [comment]
Closing as a duplicate of https://github.com/datavis-tech/vizhub-issue-tracker/issues/254, since this confusion resulted from the original confusion about being in Vim mode or not.
