### ISSUE TITLE
Drop down menu on homepage

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#372]
Size of drop down menu on VizHub home page is bigger than the one used on other sites. Example below. Compare the padding around the text too.

![dropDownAmazon](https://user-images.githubusercontent.com/13540669/86281541-b513d900-bbab-11ea-9387-381a4077781f.png)

**Comment by stushurik** [comment]
@nitanagdeote @curran not sure that is an issue, designs might be different. and as far as I know guys from stamen professional designers

**Comment by curran** [comment]
Agreed. Closing this as we're using the designed styles here.

Amazon uses styles from its own unique design language, which is consistent across the site.

The dropdown has been implemented according to the design specs by Sam Vogt, so it fits in consistently with the design language already established throughout VizHub.

**Comment by nitanagdeote** [comment]
I don't agree, its still too big box and padding and text.
