### ISSUE TITLE
"Private Icon Double" returned

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#373]
This issue is back again. 

![privateIconDouble](https://user-images.githubusercontent.com/13540669/86282987-366c6b00-bbae-11ea-9c82-7aedfb50ec31.png)

**Comment by curran** [comment]
Yeah, the fix was implemented in the live version of viz previews, which will eventually be deprecated.

This will be fixed automatically when **Real-time previews in Profile page #375** is done.

**Comment by curran** [comment]
Fixed.
