### ISSUE TITLE
'Keyword' search feature

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#374]
In addition to user name search feature a keyword search feature will be of great help, in a scenario like searching for a old viz and you don't want to search each and every viz

**Comment by curran** [comment]
How would this differ from what the search does now?

Here's an example keyword search for "map" https://vizhub.com/search?query=map

**Comment by nitanagdeote** [comment]
Well I am searching for file name "NavBar" in my profile page. I can not find it.

**Comment by curran** [comment]
Closing as duplicate of **Search within Profile** #270
