### ISSUE TITLE
A bug: too many compilation errors

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#380]
So when I am changing the code and I know what I am changing, If there is pause in writing the code it gets compiled and error is showed. If I continue like this lot of errors get accumulated and they don't go away until you refresh the page. Can not recreate the error, but happen all the time.

**Comment by curran** [comment]
Ok. The console _should_ be getting cleared out. Let me check...

**Comment by curran** [comment]
Looks like it's getting cleared. Closing as not possible to reproduce.
