### ISSUE TITLE
Search Cursor Loses Focus on Autocomplete

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#387]
The cursor selection in search box disappears, try writing other than username, the name in the list gets selected automatically and cursor is not available that time.

**Comment by curran** [comment]
Confirming this is the behavior I see as well.

@stushurik Would you be able to look at this? Looks like the first item is being automatically selected, but this should only happen after you hit the down arrow the first time. Thanks!
