### ISSUE TITLE
Create design color palette

### ISSUE THREAD

**Issue by stushurik** [datavis-tech/vizhub-issue-tracker#390]
In figma we can see
![image](https://user-images.githubusercontent.com/3383021/87243515-39354e80-c43f-11ea-9b2d-2ef56f37a139.png)
Colors mapped to some functional purpose.
In code there are a lot of hardcoded hex color codes

**Comment by stushurik** [comment]
@curran fyi

**Comment by stushurik** [comment]
the idea instead of having .some-class:hover { color: blue } // direct collor name to have .some-class:hover { color: $interactive_hover } // variable that named after some functional intention

**Comment by curran** [comment]
Good idea! I like the notion of isolating the colors in a theme definition.

**Comment by curran** [comment]
I put this together in Figma.

![image](https://user-images.githubusercontent.com/68416/101220063-ff195300-3652-11eb-8547-8bd1d361f482.png)

https://www.figma.com/file/q3jfouXPV3L5yij6qHKg6T/VizHub-%26-Course-Materials-Colors?node-id=0%3A1

@maxeneg If you end up in Figma, I think you can see and reference this set of colors in the design work.
