### ISSUE TITLE
prettier error in index.html

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#392]
![Screenshot from 2020-07-15 12-07-04](https://user-images.githubusercontent.com/13540669/87568581-e1dbec00-c693-11ea-8938-0c3183a43078.png)

**Comment by curran** [comment]
Oh no! I thought I had solved that one. I can reproduce. This is terrible.

**Comment by curran** [comment]
Finally solved! Closing this.
