### ISSUE TITLE
Move vizhub logo link to "about" in nav bar home page

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#411]

**Comment by curran** [comment]
I'm not sure what this means. Is it a suggestion to move the logo from the top left to the top right?

**Comment by nitanagdeote** [comment]
"about" button is standard webpage template feature. Now the vizhub logo click takes to the [this link ](https://datavis.tech/vizhub/) page. The logo should not be a link.
