### ISSUE TITLE
Github account for vizhub as user

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#412]
VizHub user account can be replaced for Curran's account on templates and may be on videos.

**Comment by curran** [comment]
From Sean:
>I highly recommend moving the templates that show when you Create Visualization to an account named "Vizhub" or similar. Anyone who doesn’t know who you are would probably be confused why this “Curran Kelleher” guy's stuff is there.

**Comment by curran** [comment]
Closing in favor of Teams #216
