### ISSUE TITLE
Clicking on Search Icon should Search (mobile)

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#414]
Search box moves up, autocomplete should wait little bit...if I am looking for "map" dont want user suggestion to show immediately.

**Comment by curran** [comment]
Why don't you want suggestions to show? They should not be interfering with typing (the focus issue is fixed in staging).

**Comment by nitanagdeote** [comment]
ok

**Comment by curran** [comment]
Deployed the fix for focus to production. Can you please check and see if this is still a problem?

**Comment by curran** [comment]
Main problem now: no way to execute the search on mobile.

Solution idea: make the search icon clickable, so that mobile users can do search.
