### ISSUE TITLE
Help feature redirect

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#417]
Help can be redirected to special email "vizhub@gmail.com"

**Comment by curran** [comment]
Better not gmail actually. Maybe `vizhub@datavis.tech`

**Comment by nitanagdeote** [comment]
yes something like that.

**Comment by curran** [comment]
Closing as this is covered in https://github.com/datavis-tech/vizhub-issue-tracker/issues/447
