### ISSUE TITLE
Search for word " map"

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#418]
1. searching for "map" word, does not show maps but user name. 
 
2. The cursor disappears

**Comment by curran** [comment]
Ahhh I see what you mean.

Yes, the autocomplete is for users only.

When you hit enter, the viz content results are shown.

The cursor disappearing should not be happening anymore - just deployed that fix to production (which was in staging for a few days). Please see if the cursor disappearing still happens.

Ideas for improvements:
 * Add to the autocomplete design something like "Users:", and another section that says "Hit enter to search visualizations"

**Comment by nitanagdeote** [comment]
It's working. Great!
