### ISSUE TITLE
Feedback feature idea

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#419]
On this website, the feedback button appears like this and not on all the pages. Clicking on feedback takes to nice interface.

Having feedback from the VizHub users will be great!  Feedback can go to "github Issues" for now or some other way!

The good location for feedback will be in profile page, if this design is implemented. 

![Screenshot from 2020-07-20 12-11-19](https://user-images.githubusercontent.com/13540669/87960420-475c1e00-ca82-11ea-8ec7-0b2507d35dc2.png)

**Comment by curran** [comment]
Nice! 

Link for reference: https://events.tergar.org/

When you click that, it looks like this:

![image](https://user-images.githubusercontent.com/68416/87969128-8c3a8180-ca8f-11ea-932a-ebeaf685ace9.png)

Then when you click a start, it looks like this:

![image](https://user-images.githubusercontent.com/68416/87969190-a83e2300-ca8f-11ea-951e-fcabc768acad.png)

I do like the idea of making it as easy as possible to provide feedback.

We could do something like this.

**Comment by curran** [comment]
More ideas - here's GitHub's feedback page.

https://support.github.com/contact/feedback

![image](https://user-images.githubusercontent.com/68416/87969283-d3287700-ca8f-11ea-88e0-02972b974baf.png)

**Comment by nitanagdeote** [comment]
GitHub feedback is a software field feedback interface, preferable for VizHub.
