### ISSUE TITLE
Hamburger menu for nav links in mobile  

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#420]
Usually on mobile the web page navigation bar has drop down menu. Plz check  other  "viz software" website on mobile.  Some are here
https://www.forbes.com/sites/bernardmarr/2018/06/20/comparing-data-visualization-software-here-are-the-7-best-tools-for-2018/#27b62b466d0b

**Comment by curran** [comment]
Closing in favor of the more recent https://github.com/datavis-tech/vizhub-issue-tracker/issues/624
