### ISSUE TITLE
greeting msg something like this

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#422]
Welcome to VizHub.com. Your feedback is valuable to us. Please use this form to submit any and all feedback for VizHub!

**Comment by curran** [comment]
Nice! Will do

**Comment by curran** [comment]
Done.
![image](https://user-images.githubusercontent.com/68416/87981694-aaaa7800-caa3-11ea-98c1-26f2baa57955.png)
