### ISSUE TITLE
Add "Dashboard" link in NeoNav

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#426]
Opinion: 
Profile icon can  directly take to the profile page, then user can decide from templates or other what to create. The navigation between _home_ and _profile_ is through respective buttons. 
Home button should be just before profile icon.
![Screenshot from 2020-07-20 18-13-09](https://user-images.githubusercontent.com/13540669/87991989-3ed10b00-cab5-11ea-9b26-532f39d1fc41.png)

**Comment by curran** [comment]
Pain point: it should be easier to navitate to your _own_ profile page when you're logged in.

This is addressed in the "Dashboard" link in the new designs.

![image](https://user-images.githubusercontent.com/68416/89107581-1378e500-d400-11ea-883b-c3220b594c54.png)

https://www.figma.com/file/kUpMM9rcOGg7T62tYBAN2o/Vizhub?node-id=238%3A10585
