### ISSUE TITLE
Home Page Redesign

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#428]
It will be good idea to add why VizHub?

**Comment by curran** [comment]
Can you drop a screenshot or Figma link here to the thing you showed yesterday? Thanks!

**Comment by curran** [comment]
I like this page layout. Thinking we can use their text for the call to action "Watch intro video".

![image](https://user-images.githubusercontent.com/68416/91454914-77e86200-e84f-11ea-8563-30e633306448.png)
https://worldwineregions.com/

**Comment by nitanagdeote** [comment]
WIP
https://www.figma.com/file/gopnMCgTg6J6AqnqhGYyMe/VizHub-Home-page-21Aug2020?node-id=0%3A1

**Comment by curran** [comment]
In terms of fonts and colors, here are a few ideas for inspiration/reference:

-   I'm pretty sure I'd like to stick to the existing system font stack *for the viz page*, for example <https://vizhub.com/andre6639/3588e7f46ec84939b1eef0d816363447>, as I would like that initial view when opening up a viz to be very performant.
-   I'm open to including Google Fonts on the home page and elsewhere, to give a more flashy look, at the cost of a little more bandwidth for loading the fonts
-   In the past VizHub has used [Poppins](https://fonts.google.com/specimen/Poppins), and this font is also embedded in the Datavis 2020 educational material (slides) - might be a good choice to bring it back
-   Also [Comfortaa](https://fonts.google.com/specimen/Comfortaa) is in use already, associated with "Datavis Tech"
-   For code and code-like things, I love [Ubuntu Mono](https://fonts.google.com/specimen/Ubuntu+Mono?query=ubuntu). This is also embedded in the Datavis 2020 educational material, typically with `cyan` as the color.
-   For design/color/font reference: [Datavis 2020 Slide Headers](https://docs.google.com/presentation/d/1VoWFp8vPsj6_t5bo_XtKFVALk6zrFbu7Uwca-QMZBZs/edit#slide=id.gb0b05fb4ab_0_12)
