### ISSUE TITLE
Staging site: "send feedback" remove

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#435]
"send feedback" link  on home page can be removed, got "feedback"  on the side

**Comment by curran** [comment]
On which page? We want it for some pages and not others.

I'm thinking to just remove it from the viz page, meaning pages like this https://staging.vizhub.com/curran/ae6b511a5b5147569d33a3b1cbec3d95

**Comment by nitanagdeote** [comment]
send feedback on the banner of home page
![Screenshot from 2020-07-23 16-01-05](https://user-images.githubusercontent.com/13540669/88333172-c1e4a200-ccfd-11ea-9257-de939b7eaf46.png)
