### ISSUE TITLE
Disable Feedback in Viz Page

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#437]
![image](https://user-images.githubusercontent.com/68416/88297167-98138700-cccd-11ea-90b7-f8255ccc4805.png)

**Comment by nitanagdeote** [comment]
Moving it to the bottom right may work.

**Comment by nitanagdeote** [comment]
Usually there is lot of space available on the bottom right, in most of the viz pages. Supporting the idea of keeping **Feedback** on each page.
![Screenshot from 2020-07-23 16-05-20](https://user-images.githubusercontent.com/13540669/88333508-5b13b880-ccfe-11ea-91ef-bb07f9662123.png)

**Comment by nitanagdeote** [comment]
![Screenshot from 2020-07-23 16-09-19](https://user-images.githubusercontent.com/13540669/88333859-e4c38600-ccfe-11ea-95af-adc4de047b25.png)

**Comment by curran** [comment]
Indeed, maybe the position of the button can be moved for this page.

Bottom right corner perhaps?
