### ISSUE TITLE
Home Page - banner and Navbar

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#442]
There is space between Banner and Navbar in staging home page
![Screenshot from 2020-07-24 14-17-41](https://user-images.githubusercontent.com/13540669/88422891-ec476580-cdb8-11ea-8f47-576ab6358c1d.png)

And no space in Stamen's design

![Screenshot from 2020-07-24 14-23-11](https://user-images.githubusercontent.com/13540669/88423105-3f211d00-cdb9-11ea-815e-0b7a889cf75a.png)

**Comment by curran** [comment]
Good call. I would like to implement the new designs on this one.
