### ISSUE TITLE
exit search mode

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#443]
![image](https://user-images.githubusercontent.com/13540669/88574673-aab0f780-d010-11ea-9069-481dd39754ae.png)
How to exit this stage of search. Usually clicking anywhere on the page exits search but not in vizhub

**Comment by curran** [comment]
Good catch. I've been meaning to open an issue for this. I have noticed it as well.

**Comment by curran** [comment]
Desired behavior:
 * clicking anywhere outside the menu should close it
 * Escape key should also close it
