### ISSUE TITLE
There is an issue with search box. Just try it.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#451]

**Comment by stushurik** [comment]
@nitanagdeote fixed by https://github.com/curran/vizhub/pull/337
@curran update staging please

**Comment by curran** [comment]
I just updated staging to the latest. I do see some odd things.

![image](https://user-images.githubusercontent.com/68416/89709115-fb96e900-d94a-11ea-9873-ebbc5db10c67.png)
