### ISSUE TITLE
auto-mpg.csv dataset link broken

### ISSUE THREAD

**Issue by lukasmeirelles** [datavis-tech/vizhub-issue-tracker#459]
Hi!

I believe this URL is broken: https://vizhub.com/curran/datasets/auto-mpg.csv

Got this error on my response: 
{"error":{"message":"this.database.getDataset is not a function"}}

**Comment by curran** [comment]
Oh wow, thanks for this catch! Indeed, we removed the Dataset feature from VizHub, but maybe some vizzes use data from it so we can look at bringing it back for backward compatibility. Thanks for reporting!

**Comment by curran** [comment]
@lukasmeirelles We fixed this. Thanks for reporting!
