### ISSUE TITLE
Resolve users based on email ID

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#463]
The idea here is to resolve VizHub users based on email ID when they authenticate, so that when one person authenticates via multiple authentication providers (e.g. first with GitHub, then with Facebook), where will only be one VizHub user for each person. Currently with the Facebook and Google auth flows, each provider uses a different ID for users, so currently multiple VizHub users get created for the same person if they auth using multiple providers.

**Comment by kalpesh05** [comment]
Sorry , i forgot to inform you that i made new PR yesterday
