### ISSUE TITLE
Login issue

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#477]
for the past week or so I can't log in into my account. I don't have errors of any kind, it's just an infinite signing in process. So far, I tried different things - new account, different computer/browser,  checking my github settings,  but nothing seems to fix the problem..

From Marko MTL YouTube comment https://www.youtube.com/watch?v=Ia_DwVMXwgk&lc=UgyGG-pgPsjTPvaeNzp4AaABAg&feature=em-comments

**Comment by beauMarko** [comment]
I managed to sign in this morning. It looks like everything works fine now.

**Comment by curran** [comment]
Thanks @beauMarko ! I reverted to a previous version. I'll keep this issue open as we investigate the cause.

Also CCing @Tom-S82 here who also has this login issue.

It seems to only happen to some people, while others can log in fine.

**Comment by curran** [comment]
Details of the error

```
TypeError: Cannot destructure property `email` of 'undefined' or 'null'.
    at ErrorResponse (/home/ubuntu/vizhub/packages/controllers/src/Error/ErrorResponse.js:11:9)
    at toErrorResponse (/home/ubuntu/vizhub/packages/controllers/src/Error/toErrorResponse.js:4:3)
    at /home/ubuntu/vizhub/packages/controllers/src/jwtAuth/routes/createAuthController.js:30:18
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
```

@kalpesh05 Any ideas?

**Comment by kalpesh05** [comment]
@curran is that user marked " keep my email address private "

**Comment by curran** [comment]
@kalpesh05 These are the two users who reported this:
 * https://github.com/beauMarko
 * https://github.com/Tom-S82

**Comment by kalpesh05** [comment]
@curran made changes on today's commit on same branch , you can look at it

**Comment by curran** [comment]
Ok, we've deployed a change that we think will fix the issue, on staging for now.

@beauMarko and @Tom-S82, can you please try logging in here and let us know if you can log in without issues? Thanks!

https://staging.vizhub.com/

(note this is the staging site, not normal VizHub)

**Comment by curran** [comment]
FWIW the reason for the difficulty was because we had not handled the case of the email address being marked as private.

**Comment by beauMarko** [comment]
I've just logged in to the staging site without any problems. It works fine.

**Comment by curran** [comment]
Excellent! Thanks @beauMarko for testing.

**Comment by curran** [comment]
This has been resolved. Closing.
