### ISSUE TITLE
In mobile version, icon hovering feature is not available, so you don't know you are on the icon or not

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#489]

**Comment by curran** [comment]
@nitanagdeote Can you please elaborate on how this plays out? In general it's true, but I'm not sure what specific instance where it matters. For example what specific icon were you looking at with this? Thanks!

**Comment by nitanagdeote** [comment]
I was trying to fork. When I was on fork, it did not have "icon hover effect" like in desktop version of vizhub.

**Comment by nitanagdeote** [comment]
Just checked again, if you press on icon properly then it shows "icon hover effect", sometime it  shows the effect , sometime it doesn't

**Comment by curran** [comment]
What do you propose we do to improve it?

**Comment by nitanagdeote** [comment]
It will be better if it shows hover effect on even slight touch on the icon. Did you try it on mobile?

**Comment by curran** [comment]
So if you tap the fork icon once, it should show like it's hovered, and if you tap it again it should fork? So 2 taps would be required to fork? I did try it.

**Comment by nitanagdeote** [comment]
Its not clear, if one tap is required or two taps are required.

**Comment by curran** [comment]
Closing this as the current design I believe addresses this issue.

Current design: when you click the Fork icon, it shows a dialog that you can either move ahead with or cancel. If you don't know what the icon is and you click on it, the dialog appears, and you now understand what the icon is for. Then you can cancel it. So the dialog itself acts like a teaching tool (tooltip) that educates the user as to what the icon does.
