### ISSUE TITLE
On the profile page...the layout of private and public viz needs t be change.Now you see public viz only on top of the page

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#507]
![publicPrivate](https://user-images.githubusercontent.com/13540669/95623579-87102180-0a43-11eb-9cf9-92b6ce143f22.png)

**Comment by curran** [comment]
The current behavior feels right:
 * Private sidebar button is visible only when viewing your own profile and logged in.
 * Otherwise, private sidebar button is visible.

Closing that as it's unclear what the desired change is. Feel free to reopen and clarify!
