### ISSUE TITLE
Saved globally

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#514]
what is it? saved globally
![savedGlobally](https://user-images.githubusercontent.com/13540669/96769542-443c3b00-13ad-11eb-8efc-289b24a48909.png)

**Comment by curran** [comment]
It means the changes were saved. If you change some code you'll see it switches to "Saving..." then "Saved globally".

We might want to change it to just say "Saved".

Google Docs says something like "All changes saved".

**Comment by nitanagdeote** [comment]
All changes saved is better.

**Comment by curran** [comment]
Changed to just "Saved".
