### ISSUE TITLE
Private viz is gone

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#531]
![privateVizDisappear](https://user-images.githubusercontent.com/13540669/96930206-58ee0100-1489-11eb-83d5-59a0934d27f6.png)

**Comment by curran** [comment]
OK - yes, this happened before with a paying customer. I think something about the authentication flow clobbers the `plan` field, which is terrible. This is something we need to fix, indeed.

I've restored it for you just now by manually changing the database, but I totally agree this should never happen and it's a pretty severe bug.

**Comment by curran** [comment]
Note to future self - I need to check if this happened with all the current paying customers and make sure their plan status is restored.

**Comment by curran** [comment]
I think it's localized to `packages/useCases/src/interactors/updateUser.js`. We need to preserve the `plan` value from before the authentication update.
