### ISSUE TITLE
redCrossEditor

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#532]
Not showing all the red cross icon. When I delete this line shows next icon.

![allRedCross](https://user-images.githubusercontent.com/13540669/96932268-9bfda380-148c-11eb-92cb-d27804bcc877.png)
Link to viz
[here](https://staging.vizhub.com/nitanagdeote/e12bd46aa6094d428c0a25fce1f35755?edit=files&file=index.js)

**Comment by stushurik** [comment]
@nitanagdeote in example you provide, red cross indicates that it is not valid js syntax (const and the new line is not valid)

**Comment by curran** [comment]
I think it's the behavior of ESLint, to stop parsing when it encounteres a syntax error. So the errors later in the code will not show up unless that fist one is fixed. The line is correct - that's where there is a syntax error.

**Comment by stushurik** [comment]
@curran In IDE it works same way

**Comment by curran** [comment]
Good to know!

**Comment by nitanagdeote** [comment]
@stushurik got it. 
@curran  error is on line 8 or 9? confusing ?

**Comment by curran** [comment]
Error is actually on line 9, yes. It's because the following _is_ valid JavaScript:

```js
const
foo = "bar";
```

**Comment by nitanagdeote** [comment]
Still learning javascript!

**Comment by curran** [comment]
Closing as not a VizHub bug.
