### ISSUE TITLE
SEO for Home Page

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#533]
Google search for vizhub does not have proper description like other platforms. Comparing vizhub with Tableau search result.
![vizHubGoogle](https://user-images.githubusercontent.com/13540669/97050530-84d1bb00-154b-11eb-8f9a-e7d24b4fb84a.png)
![tableauSearchGoogle](https://user-images.githubusercontent.com/13540669/97050542-8ac79c00-154b-11eb-9015-25cfb0e619fe.png)

**Comment by curran** [comment]
This is a great idea. Low hanging fruit I'm pretty sure.

We can utilize meta tags.

**Comment by nitanagdeote** [comment]
Awesome!

**Comment by stushurik** [comment]
@curran https://support.google.com/webmasters/answer/47334?hl=en
