### ISSUE TITLE
More aggressive Prettier

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#579]
Problem: code gets cut off on the right of the editor, when opened with all default settings and 100% browser zoom.

![image](https://user-images.githubusercontent.com/68416/99685888-0fc1aa80-2a51-11eb-9a65-2b6b9dfc14a9.png)

Proposed solution: change the max line length in our Prettier config fom 80 (current value, Prettier default) to 60 (where the code actually gets cut off).

This change would also help the use case of snippet embedding, where the width of the snippet embed is low.

**Comment by stushurik** [comment]
@curran we can take prettier config from package.json so users would be able to adjust it as they wish

**Comment by curran** [comment]
Great idea! We can track that separately. This issue is about the default.

**Comment by stushurik** [comment]
> Great idea! We can track that separately. This issue is about the default.

@curran I would even go father and suggest removing settings modal and moving all settings (viz height, privacy) to package.json

**Comment by curran** [comment]
An interesting idea!!

We can have a new field, maybe called `vizhub`.

We can use it to track the mapping from package name to globals as well.

Hey - maybe we can use this also to drive the license!

Lots of issues can be solved with this direction.

**Comment by curran** [comment]
This issue is done, default prettier character count was reduced.

Created a new issue to capture the other ideas: Move more config to package.json #737
