### ISSUE TITLE
Feature suggestion: Star your viz

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#610]
I would like to STAR my particular viz (the one with a lot of annotations). When it starred, it can move to collections or on the top of the profile page.
Why I need this feature: All my Vizs with a lot of annotations (which I need to access frequently) are lost in the other Vizs.

**Comment by curran** [comment]
Maybe we can use the existing upvote feature?

Something missing from the upvote feature is the ability to see a list of vizzes you have upvoted in the past.

That page could maybe have a section for your own vizzes that you've upvoted.

**Comment by curran** [comment]
Profile page will get the ability to sort by upvotes one day - maybe that would solve this case.

**Comment by stushurik** [comment]
@curran @nitanagdeote i think star feature is great idea! i think it might span over annotation. User might mark some favorite vizzes so user can get easily get access to them (instead of searching or sorting). Moreover I can think about "follow" feature: if user follow some user might receive updates by email (e.g. the diff, or changes made during the day e.t.c)

**Comment by nitanagdeote** [comment]
> Moreover I can think about "follow" feature: if user follow some user might receive updates by email (e.g. the diff, or changes made during the day e.t.c)
That is a good idea!

**Comment by nitanagdeote** [comment]
> Profile page will get the ability to sort by upvotes one day - maybe that would solve this case.

I specifically want to STAR my private Vizes. It's going to be my thing not public!
and I am not that much interested in upvotes. I think it needs remake!

**Comment by nitanagdeote** [comment]
I really need this feature for my private vizes.

**Comment by curran** [comment]
Closing in favor of #673
