### ISSUE TITLE
Blog Post on Snippet Embed

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#616]

**Comment by sriramvsharma** [comment]
I have a draft of the announcement here.

https://vizhub.com/blog/wp-admin/post.php?post=3329&action=edit

I think we should hold the announcement until we can fix the issue with not being able to do multiple highlights in a snippet.

**Comment by sriramvsharma** [comment]
There are a couple of typos - "Edit in vizhub" - Vizhub is in lowercase. 

"required" is misspelled as "requried".

**Comment by curran** [comment]
This is great stuff @sriramvsharma ! Thanks for surfacing these points.

**Comment by sriramvsharma** [comment]
The embed works on Vizhub's Readme.md markdown page, but I am unable to embed the snippet on Github. 
https://github.com/sriramvsharma/vizhub-code-annotations/blob/master/README.md


![image](https://user-images.githubusercontent.com/6435829/101622557-0da59880-39cc-11eb-85e9-2087d5603cdc.png)

Is it possible or does each site have to whitelist Vizhub to allow this? @curran

**Comment by curran** [comment]
I think GitHub is setup to not allow iFrame embeds at all, from any site, in the README documents. I dont think a YouTube embed would work either.

**Comment by curran** [comment]
Just needs:
 * Polishing
 * Review / copy editing - maybe @maxgraze can do this
 * Credits to Oleks and others
