### ISSUE TITLE
Same viz so many times on home page.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#618]
This looks strange.
![soManyThubnails](https://user-images.githubusercontent.com/13540669/101090006-fe65bb80-3583-11eb-9dba-674095e722df.png)

**Comment by curran** [comment]
Looks like someone just trying out VizHub. https://vizhub.com/descarmendel

What is the action we can take here? Anything to be done for this?

Seems like this sort of thing will go away from the home page if we implement the ranking algorithm #478 .

**Comment by waseem-medhat** [comment]
Maybe a curated section, say "Visualizations of the Week (or Month)", to maintain the prettiness of that first visible region that users land on. Then they could scroll to the section of "most recent" just the way it is already implemented right now.

![image](https://user-images.githubusercontent.com/41170102/101488906-e073ce80-3968-11eb-80b9-72eecccd673b.png)

**Comment by curran** [comment]
Yes yes yes! Happy to hear from you about this @waseem-medhat . It's a great idea.

Also tracked as #590

**Comment by stushurik** [comment]
@curran @waseem-medhat I believe this one will also solve the issue https://github.com/datavis-tech/vizhub-issue-tracker/issues/615

**Comment by waseem-medhat** [comment]
Nice... And both ideas can be combined together, having the visualizations upvoted by @curran appear at the top of the page but in a separate section instead of sorting the recent projects.

**Comment by curran** [comment]
Closing as this is solved by "sort by popular" as default sort.
