### ISSUE TITLE
Handle newlines in the title

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#619]
I have a title and I used prettier after that it shows untitled.
https://vizhub.com/nitanagdeote/53a8ddadf4894e97846cc8f28abc509e?edit=files&file=index.html&line

**Comment by curran** [comment]
Nice catch! It's a valid bug.

![image](https://user-images.githubusercontent.com/68416/101260364-52e07680-36fd-11eb-9d82-c705fda4fa33.png)

I think our title detection assumes that the title tag will be on a single line only.

It should be technically possible to get at the title text even if it is authored as multiple lines.

**Comment by curran** [comment]
Calling out that this tends to surface after running Prettier, which splits long titles into multiple lines.
