### ISSUE TITLE
I always come across this error but can not reproduce

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#640]
Sometimes if I have a lot of errors. Even I fix the code after that the error is still there. The code should be working but it doesn't. Then I refresh the page and it works. And I don't know how to reproduce this.

**Comment by curran** [comment]
Try to reproduce please. Even in general terms. If we can't reproduce it we can't fix it.

**Comment by waseem-medhat** [comment]
It occasionally happens with me, too. My guess is that the auto-reload breaks after too quick (or too frequent) changes in the code before a reload is done. Maybe we can confirm or at least rule it out with the auto-run toggle.

**Comment by curran** [comment]
Good to know! I wish I had a sequence of specific steps to follow to reproduce it. Then we can look more deeply into what's going on.

**Comment by curran** [comment]
Would love to reproduce and fix this.

**Comment by curran** [comment]
Closing as cannot reproduce.
