### ISSUE TITLE
I got a horizontal bar in the editor.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#644]
![barInCode](https://user-images.githubusercontent.com/13540669/101686103-9822e200-3a36-11eb-9986-03ca3c027665.png)
Can not get rid of it.

**Comment by curran** [comment]
Try clicking on the line number on the left. Looks like that line is highlighted.

**Comment by curran** [comment]
Closing in favor of #344
