### ISSUE TITLE
Address Datavis 2020 linter warnings

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#647]
The datavis 2020 page is giving some linter warnings. This issue is about making the code changes required to eliminate all of those warnings.

![image](https://user-images.githubusercontent.com/68416/101906605-3756ef00-3b87-11eb-85e7-22248f6e1597.png)

**Comment by sriramvsharma** [comment]
Just pushed a commit addressing them. 

https://github.com/curran/vizhub/commit/3151b7b3fb65fb5906f7d20e0a975ab6e691f00d

How do I check for these linter errors btw? I use ESLint, but it throws this error: 

"Failed to load plugin 'react' declared in '.eslintrc.js': Cannot find module 'eslint-plugin-react' Require stack: - /Users/Sriramsharma/Documents/vizhub/__placeholder__.js Referenced from: /Users/Sriramsharma/Documents/vizhub/.eslintrc.js"

**Comment by curran** [comment]
Thanks for this! I created a pull request for this, resolved merge conflicts, and merged.

https://github.com/curran/vizhub/pull/410/

In future, please open a Pull Request in a new branch, branched off `master`.

The ESLint errors were solved recently. If you branch from the latest in `master`, the errors should go away.
