### ISSUE TITLE
Viz Info endpoint does not respect ordering of IDs

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#652]
The endpoing powering the create-viz page does not return viz info documents in the same order as the IDs that were passed in.

Desired behavior: the ordering of the returned vizInfo documents should match the ordering of the IDs passed in.

This is so we can control the order in which the IDs are presented on pages.

**Comment by curran** [comment]
Use case: solving this will unblock release of the new create-viz page.

**Comment by stushurik** [comment]
@curran 
I think there are 3 ways how it can be implemented:
1. sort on the mongo side. it requires "aggregate" or "map-reduce" - https://stackoverflow.com/a/22800784
2. fetch documents from mongo and sort them using javascript on the backend (e.g in the packages/useCases/src/interactors/getVisualizationInfos.js interactor)
3. sort on the client-side

If we take in to account that a) you want control the vizes` order in the  "create viz" page, b) the size of collection is small and c) you want to reduce server costs I would suggest go with option 3 -- client side sort.

What do you think about it?

**Comment by stushurik** [comment]
@curran and please merge https://github.com/curran/vizhub/pull/407

**Comment by curran** [comment]
Agree, client side sorting seems a reasonable approach.
