### ISSUE TITLE
text notes in editor

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#669]
![notes](https://user-images.githubusercontent.com/13540669/102826797-60f5ee80-43af-11eb-9aa1-367bc73888c0.png)
This will solve the problem of taking notes. The default notes.txt file in the editor.

**Comment by curran** [comment]
Closing as it's possible for anyone to create a `notes.txt` file and use it for notes.

Also possible to put notes in the README, or in code comments.

I like to stick to the idea that the vizzes are the templates, and that the platform should not automatically add or remove any files.

That said, there may be some good use cases around Annotations, which I'd like to track as #444
