### ISSUE TITLE
[package.json] Custom License

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#67]
As a visualization author, I want to specify which license the code is released under, so that I may change it from the default MIT License.

**Comment by micahstubbs** [comment]
An Apache-2.0 default license would allow a few more people to use VizHub examples at work.

as I understand it, MIT is silent on patent grants, while Apache-2.0 explicitly grants a patent license to users. 

If you the author have no patents, then Apache-2.0 is a way of signaling to paranoid users that you don't plan to use secret patents to sue them later.

**Comment by micahstubbs** [comment]
outside of the "people who work at companies with lawyers" cohort, MIT is friendly and fine.  it is also much more concise than Apache-2.0.

**Comment by curran** [comment]
@micahstubbs Thanks for the insight! Maybe the default should be changed, as the desire is to make it as permissive as possible.

**Comment by curran** [comment]
Ideas for how to do this:

 * Support a `LICENSE` file, like GitHub does.
 * Add a piece of config to the viz itself, and provide users a menu for selecting between various licenses, like Blockbuilder does.

**Comment by curran** [comment]
This is becoming important as people are starting to port things from Observable (ISC Licensed) to VizHub (MIT Licensed).

**Comment by curran** [comment]
New idea for how to approach this: use the `license` field of package.json.

https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license

VizHub can read that and display the license where it currently says "MIT License".

The lookup table from License code to full form is here https://www.npmjs.com/package/spdx-license-ids

**Comment by curran** [comment]
If we use the `license` field of package.json, it will not be possible to simply change the license on old vizzes that do not have a `package.json`.

It seems that the best approach to this would be to add an additional section of the settings panel with a dropdown for licenses.

Let's add a menu there with the following set of options:

**Comment by stushurik** [comment]
@curran do you have a case for old vizz which requires a license change?
Why do we need to complicate things, just for some hypothetical use case?

**Comment by curran** [comment]
Good call out. It's true there is no strong use case for changing the license on existing vizzes.

**Comment by curran** [comment]
Maybe a simple implementation based on `package.json` would be best after all.

**Comment by curran** [comment]
Here's a rough design I threw together.

![image](https://user-images.githubusercontent.com/68416/102267428-e11be000-3ee7-11eb-94a3-a5a9248f69cd.png)

**Comment by curran** [comment]
The license field in `package.json` is well established, maybe we would be best off using it.

Some nice documentation about it: https://docs.npmjs.com/cli/v6/configuring-npm/package-json#license

**Comment by curran** [comment]
@stushurik Please move ahead with the following scope of work for this issue:
 * Develop some logic that recognizes the `license` field of `package.json`.
 * Use that to change the license text displayed at the bottom of the viz page.
