### ISSUE TITLE
[package.json] Iterate Exported Files

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#672]
When package.json is present and the viz is exported, there are currently a few issues.

 * The `index.html` does not include the `bundle.js` build at all, so it does not actually run unless the user adds the script tag manually in there.
  * `npm run build` does not seem to work out of the box.
  
![image](https://user-images.githubusercontent.com/68416/102924463-978b4200-445f-11eb-9536-279e572103d5.png)
I saw this error, not sure how to resolve it.
  
  * If the build did work, the `bundle.js` that is included in the export is different from the one that would be generated, because it does not include the full JS of dependencies.
  
  
I propose we do the following:

 * In the export, we provide the `index.html` that VizHub generates internally, which _does include_ the `<script>` tags that pull in `bundle.js`, and also the ones that pull in dependencies from UNPKG.
 * In the exported Rollup config, treat dependencies as external, so that when the user runs `npm run build`, it would generate the same lightweight bundle that VizHub would generate.
 
The alternative option would be to go all-in with providing users an exported thing that takes full advantage of NPM and actually bundles installed dependencies into the build. This is a "nice to have", and seems to be more trouble than it's worth. If we did this, we'd need to do a lot more work to make sure:
  * The export should be runnable if you just drop the files into a static file server.
  * The `npm run build` command works in all cases
  * The exported bundle should be the same as the one that `npm run build` would generate, so I guess we'd need to generate it server side or something... This seems like way too much work.
  
So, after this is all working, I think whatever confusion remains can be clarified with a blog post that documents what users can do if they do want to switch to using a Rollup config that bundles dependencies into the build. This is a change that users can do manually if they want to. We just need to provide them something that works out of the box, even if it is a little unconventional (e.g. using UNPKG to pull in dependencies).

**Comment by stushurik** [comment]
@curran could you provide a link to a broken viz?

**Comment by curran** [comment]
https://staging.vizhub.com/curran/650134e6764d4ae3aa29b4e2f0b8e578?line

(on another note - I notice `line` appears in the URL all the time)

**Comment by stushurik** [comment]
@curran we need to choose: leightweight vs npm bundling

**Comment by curran** [comment]
Let's go with lightweignt. Done. Final answer.
