### ISSUE TITLE
Silly error

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#692]
This happens when I use prettier on the index.html
I first thought it may have happened due to something else and deleted all the code in index.js
![SchittCreak](https://user-images.githubusercontent.com/13540669/103945214-d9c0ae80-5102-11eb-9705-66e3b50b1839.png)

**Comment by curran** [comment]
Duplicate of https://github.com/datavis-tech/vizhub-issue-tracker/issues/686
