### ISSUE TITLE
Private section in profile does not show all Private vizzes

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#708]
Pagination needs to be handled separately for public and private sections.

**Comment by nitanagdeote** [comment]
Not sleeping?

**Comment by stushurik** [comment]
@curran as for me, infinite scroll is not a good choice for the profile page. It's hard to navigate in such an infinite list. Imagine that you find something on page 3, then decide to go a few pages further, and then you decide to go back. if there are page/links to pages, it is easy to do that. With an infinite list, it is hard to find previous point
