### ISSUE TITLE
Task feature in the editor

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#715]
Like, google docs task feature to note down what are the tasks for that viz will be good.
![tasks](https://user-images.githubusercontent.com/13540669/106332913-a7175b00-6255-11eb-820e-c86653c7c2bc.png)

**Comment by curran** [comment]
Related to #496 

If that were done, then you could add checkboxes to the README and it would look like this:

 * [X] Task 1
 * [ ] Task 2
 
By writing this code:

```md
 * [X] Task 1
 * [ ] Task 2
 ```
 
 Then clicking the checkboxes would edit the text automatically. I think this would be a good approach to adding tasks.

**Comment by curran** [comment]
Closing in favor of #496
