### ISSUE TITLE
Account Page First Pass

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#716]
As a user, I want to able to know what my current plan is.

Design ideas:
 * Add a new menu entry to the user dropdown.
 * When the user clicks on that, it takes them to a new page under `vizhub.com/account`.
 * That page should tell the user what plan they are currently on, based on the `plan` value of the User entry.
 
The first version of this page can be extremely basic, just putting text on the screen with no thought to design, just to get the mechanics in place. A second pass can focus on design. The design work itself can be done separately or in parallel to the first working version of the page.

This feature should be behind a feature flag, so that we can enable it in staging but not production, until we are ready with the second pass of the page.

**Comment by stushurik** [comment]
@curran as for me there is no point to create a page just for one word
Check out this design, we can do something similar:
![image](https://user-images.githubusercontent.com/3383021/106899019-8b043580-66fd-11eb-9c6b-58b360f7b4a3.png)
![image](https://user-images.githubusercontent.com/3383021/106899055-93f50700-66fd-11eb-8813-34126f7a9847.png)


Or we can add a label (pink badge like private badge) somewhere here:
![image](https://user-images.githubusercontent.com/3383021/106899334-e9311880-66fd-11eb-9866-5a654707e12e.png)

**Comment by curran** [comment]
>no point to create a page just for one word

Indeed - sorry I did not express clearly the larger intent of the page - I'm thinking that this Account page is where you can upgrade or downgrade your plan as well. So the first pass is laying the foundation for that.

**Comment by stushurik** [comment]
Ok
