### ISSUE TITLE
On the total no of the forks page, the title and previews require more spacing.

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#723]
![more_space_between titile and image](https://user-images.githubusercontent.com/13540669/107284905-6d500c80-6a2c-11eb-84ff-0424ea79b91e.png)

**Comment by nitanagdeote** [comment]
@curran I am not sure about the location of this page in the vizhub files? would like to modify it!

**Comment by curran** [comment]
Great idea! This is in `/packages/neoFrontend/src/pages/ForksPage/index.js`. PRs welcome :)

**Comment by curran** [comment]
Closing in favor of https://github.com/datavis-tech/vizhub-issue-tracker/issues/745
