### ISSUE TITLE
Private Vizes page: Clicking on the "most recent" option takes to the public viz page

### ISSUE THREAD

**Issue by nitanagdeote** [datavis-tech/vizhub-issue-tracker#724]
"most recent" is not working

**Comment by curran** [comment]
I can reproduce:
 * Go to private section
 * Change sort order
 * Observe navigation to public.
 
The technical issue is perhaps that the route is changed in two places, the sort order and the section, and these don't talk to one another.

Suggestion for approach: unify the routing logic, in the same style as the viz page.

See `src/pages/VizPage/URLStateContext/reducer.js` for the pattern that we can perhaps use for the profile page as well.

**Comment by curran** [comment]
I'd be happy to copy-paste the overall structure of `URLStateContext` for the profile page.
