### ISSUE TITLE
bundle.js not updating

### ISSUE THREAD

**Issue by kalmdown** [datavis-tech/vizhub-issue-tracker#760]
Am trying to work through the CSS Color - Radial lesson. I forked the CSS Named Color loader and started to edit it. Making changes in index.js is not changing the output. Looking at bundle.js it is still the same as before forking. 

index.js 
![image](https://user-images.githubusercontent.com/2244894/127037668-841d9c33-a21e-4fe6-a4b1-46ed19a51c2a.png)

bundle.js
![image](https://user-images.githubusercontent.com/2244894/127037825-062f6c78-e35d-4648-b305-5fd7c3e2d39a.png)

**Comment by curran** [comment]
Thanks for reporting!

If you open the console, are there any errors?

**Comment by curran** [comment]
Also, `bundle.js` is not editable, because it is a derived file. If you want to change it, change `index.js` and it will update automatically.

**Comment by kalmdown** [comment]
I understand that it is not editable but I assumed that bundle.js is what gets rendered, because what was being rendered was what was in bundle.js, not my code.

I had done a Clear Cache and refreshes and the problem stuck around. When I checked, there were a number of "Forbidden 403" error messages that suddenly cleared up ... so I can't pursue why it was happening now.

**Comment by curran** [comment]
Can you share a link to the viz that's causing the issues? I can investigate.

**Comment by kalmdown** [comment]
https://vizhub.com/kalmdown/5e90574ec98c44b58fdfb028b351fadf?edit=files&file=index.js

Nothing is rendering and I get no console output or errors. Get two issues:
![image](https://user-images.githubusercontent.com/2244894/127046337-37f4cb3f-a824-436c-abd3-411bcf034aa3.png)

**Comment by curran** [comment]
Your program seems to be running just fine.

![image](https://user-images.githubusercontent.com/68416/127050384-6381d333-b052-4b3c-86ae-3b9c91b1a420.png)

Try `backgroundColor` instead of `backgroundcolor`.

**Comment by kalmdown** [comment]
Changed, but still no joy.

![image](https://user-images.githubusercontent.com/2244894/127055487-c7557ef5-d114-48f3-9b50-640ffa917d6d.png)

**Comment by curran** [comment]
Try `backgroundColor: d['RGB hex value'], `

![image](https://user-images.githubusercontent.com/68416/127064100-3266a4d3-45f3-41e0-9f5e-b0034d8b4d9e.png)

You had `backgroundColor: d['RGB Hex value'], `

The field name did not match - upper case vs. lower case H.

**Comment by kalmdown** [comment]
Any way to get better debugging tools - like something that can compare similar data names and point that out?

**Comment by kalmdown** [comment]
And...thanks for debugging" Sorry to have listed as a defect. The problem with browser based IDE's is knowing where the error is coming from - your code, the IDE, proxy issues, browser issues... Not knowing where issues like this come from is a huge blocker for learners and very discouraging. Having ways (teaching tools) to help get over "invisible" errors can help keep them/us on track and be less discouraged.

**Comment by curran** [comment]
Indeed, I agree. The Chrome developer tools are the best bet that I know of these days. I have made my best effort to have VizHub surface exact files and line numbers for errors (using sourcemaps), but yes, always looking for ways to improve it!

I don't think any debugging tool exists today that is sufficiently advanced to detect something like that bug you had with the capitalization, and suggest a fix. If you know of anything like that, I'd be curious to see it!

**Comment by kalmdown** [comment]
The reason I felt that particular defect was catchable is that the name came from the data. So the context to check is much smaller than _any variable_. Because it was under **d** the expected correct variables is a short list and if something is close but only off by capitalization or minor spelling it would be worth asking user if they meant something else. Similarly checking against variables within context and a few degrees outside (user's imports but maybe not external ones) to see if any are similar should be easy.
