### ISSUE TITLE
Delete Dataset

### ISSUE THREAD

**Issue by curran** [datavis-tech/vizhub-issue-tracker#89]
As a dataset author, I want to delete a dataset, so that it won't be there anymore.

Please :+1: this issue to help prioritize this task in our [backlog](https://github.com/datavis-tech/vizhub-ui/issues?q=is%3Aissue+is%3Aopen+sort%3Areactions-%2B1-desc).

**Comment by leorawe** [comment]
I just uploaded a whole bunch of avocado datasets - I finally deleted all the quotes and the hyphens (that may or may have not been the issue), and the dataset worked.  So now I have stray datasets.  Would be nice to delete the ones that don't work.

**Comment by curran** [comment]
Thanks @leorawe for the info! Good to know this would be useful. Will prioritize this.
